# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "giflw/rockylinux"

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y buildah podman
  SHELL
end
